---
- name: Install Docker and deploy container for different OS
  hosts: all
  become: true
  tasks:

    - name: Gather the OS type
      ansible.builtin.setup:
        filter: ansible_facts.distribution

    - block:
        - name: Install Docker for Ubuntu
          apt:
            name: docker.io
            state: present
            update_cache: true
          when: ansible_facts.distribution == 'Ubuntu'

        - name: Start Docker service for Ubuntu
          service:
            name: docker
            state: started
            enabled: true
          when: ansible_facts.distribution == 'Ubuntu'

        - name: Add ubuntu user to the docker group (Ubuntu)
          user:
            name: ubuntu
            groups: docker
            append: true
          when: ansible_facts.distribution == 'Ubuntu'
      when: ansible_facts.distribution == 'Ubuntu'

    - block:
        - name: Install Docker for Amazon Linux
          yum:
            name: docker
            state: present
            update_cache: true
          when: ansible_facts.distribution == 'Amazon'

        - name: Start Docker service for Amazon Linux
          service:
            name: docker
            state: started
            enabled: true
          when: ansible_facts.distribution == 'Amazon'

        - name: Add ec2-user to the docker group (Amazon Linux)
          user:
            name: ec2-user
            groups: docker
            append: true
          when: ansible_facts.distribution == 'Amazon'
      when: ansible_facts.distribution == 'Amazon'

    - name: Pull the Docker image
      docker_image:
        name: felipe8617/dog_breed:v1
        source: pull

    - name: Run the Docker container
      docker_container:
        name: dog_breed
        image: felipe8617/dog_breed:v1
        state: started
        ports:
          - "8080:80"