# Utiliza tu imagen parent como punto de partida
FROM alpine_parent

# Install Nginx
RUN apk update && apk add --no-cache nginx \
    && mkdir -p /run/nginx

# copu files to nginx server
COPY ./my-app/*  /usr/share/nginx/html/index.html

#configure default.conf 
COPY ./default.conf /etc/nginx/http.d/default.conf

# Expose port
EXPOSE 80

# Command to execute
CMD ["nginx", "-g", "daemon off;"]